### PR TITLE
English usage changes to the docs: small usage changes, propper case …

### PR DESCRIPTION
**Pull request by jhomme**
…changes. Also, formatted using the Microsoft Manual of Technical Style guide.

### CODE REVIEW

**Comment by nvdaes** [comment]
Hi Jim, thanks for your work.
We are commenting this on the pull request, for instance replying to the 
notifications email.
Comments:
* Please, use 5.0 branch of this repo instead of master, since reviewers 
have to look at this first.
* Note that now, the menu item and the corresponding dialog won't be 
named Insert smiley. The name for both dialogs will be Insert emoticon.
Great work. Thanks.

**Comment by nvdaes** [comment]
Hi, finally you don't need to use 5.0 branch, as we have merged 5.0 into master to release 5.0-dev version.
Thanks.

**Comment by jhomme** [comment]
Hi,
What would you like to do with this? I can resubmit by using this and merging in the changes, then putting in another pull request if you think it would be worth doing.

**Comment by nvdaes** [comment]
Hi, please consider my comment about the name of gui elements.
Also, just if you want, I think it would be cleaner if you can use a 
topic branch instead of master.
I have other add-ons to update, one of one week, so I'm planing to 
release another version for this one perhaps one month later. Then we 
could include your changes.
Thanks.

**Comment by nvdaes** [comment]
For now, I will close this until further reply to last comment.
Thanks

**Pull request closed without merging**
